import yaml
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
FLINT_DIR = BASE_DIR / "artifacts" / "flint"
OUTPUT_FILE = FLINT_DIR / "PUBLICATION_BUNDLE_QUARTZ.md"

def load_yaml(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def main():
    print(" Compiling Quartz-Optimized Publication Bundle...")
    
    # Load all Flint artifacts
    src1 = load_yaml(FLINT_DIR / "SRC-FLINT-001.yaml")
    src2 = load_yaml(FLINT_DIR / "SRC-FLINT-002.yaml")
    src3 = load_yaml(FLINT_DIR / "SRC-FLINT-003.yaml")
    
    evd1 = load_yaml(FLINT_DIR / "EVD-FLINT-001.yaml")
    evd2 = load_yaml(FLINT_DIR / "EVD-FLINT-002.yaml")
    evd3 = load_yaml(FLINT_DIR / "EVD-FLINT-003.yaml")
    
    claim = load_yaml(FLINT_DIR / "CLM-FLINT-001.yaml")
    diag = load_yaml(FLINT_DIR / "DIAG-FLINT-001.yaml")
    
    # Generate Markdown with Quartz Callouts and Wikilinks
    md = f"""---
title: "Flint Water Crisis: Corrosion Control Failure"
date: {datetime.now().strftime('%Y-%m-%d')}
tags: [flint, water-crisis, validated, phase-9]
loom_spec: "PL-307 v1.0"
validation_status: "PASSED"
---

# Flint Water Crisis Analysis
> [!abstract] Executive Summary
> **Thesis:** {diag['thesis']}  
> **Epistemic Status:** `{diag['epistemic_status'].capitalize()}` | **Audit Status:** `{diag['status'].replace('_', ' ').title()}`

This artifact represents a fully audited, multi-source analysis of the Flint Water Crisis. Every claim below is mechanically validated and backed by a cryptographic audit trail.

---

## 1. The Core Claim
**Statement:** "{claim['statement']}"

> [!check] Validation Metrics
> - **Epistemic Status:** `{claim['epistemic_status'].capitalize()}`
> - **Verification Level:** `{claim['verification_level'].replace('_', ' ').title()}`
> - **Promotion Stage:** `{claim['promotion_stage'].capitalize()}`
> - **Contradiction Status:** `{claim['contradiction_status'].capitalize()}`

---

## 2. Evidence Chain & Source Registry

### 2.1 Primary Supporting Evidence

#### Source A: {src1['title']}
> "{evd1['extracted_content']}"  
> — *{src1['publisher']}, {src1['date']}*

<details>
<summary><strong>⚙️ View Provenance & Cryptographic Hash</strong></summary>

> [!info] Raw Metadata
> - **Object ID:** `[[{evd1['id']}]]`
> - **Source ID:** `[[{evd1['source_id']}]]`
> - **Location:** {evd1['location']}
> - **Document Hash:** `{evd1['document_hash']}`
> - **Extracted By:** `{evd1['extracted_by']}`
> - **Retrieved At:** {evd1['retrieved_at']}
</details>

#### Source B: {src2['title']}
> "{evd2['extracted_content']}"  
> — *{src2['publisher']}, {src2['date']}*

<details>
<summary><strong>⚙️ View Provenance & Cryptographic Hash</strong></summary>

> [!info] Raw Metadata
> - **Object ID:** `[[{evd2['id']}]]`
> - **Source ID:** `[[{evd2['source_id']}]]`
> - **Location:** {evd2['location']}
> - **Document Hash:** `{evd2['document_hash']}`
> - **Extracted By:** `{evd2['extracted_by']}`
> - **Retrieved At:** {evd2['retrieved_at']}
</details>

### 2.2 Contradictory Evidence & Resolution

#### Source C: {src3['title']}
> "{evd3['extracted_content']}"  
> — *{src3['publisher']}, {src3['date']}*

<details>
<summary><strong>⚙️ View Provenance & Cryptographic Hash</strong></summary>

> [!warning] Contradictory Source
> - **Object ID:** `[[{evd3['id']}]]`
> - **Source ID:** `[[{evd3['source_id']}]]`
> - **Location:** {evd3['location']}
> - **Document Hash:** `{evd3['document_hash']}`
> - **Resolution:** {claim.get('contradiction_resolution', 'N/A')}
</details>

---

## 3. Human Audit & Provenance Trail
This artifact was promoted to `{claim['promotion_stage']}` only after satisfying the PL-001 v1.1 Bootstrap Governance Rule (requiring ≥2 designated internal auditors).

> [!timeline] Audit Log
> 1. **Verification:** `{evd1['extracted_by']}` confirmed excerpt at {evd1['retrieved_at'][:10]}.
> 2. **Verification:** `{evd2['extracted_by']}` confirmed excerpt at {evd2['retrieved_at'][:10]}.
> 3. **Assessment:** `[[ACT-0001]]` resolved contradiction: *"The 2015 MDEQ statement was a premature political assurance..."*
> 4. **Promotion:** `[[ACT-0001]]` promoted claim to `{claim['promotion_stage']}`.
> 5. **Independent Audit:** `[[ACT-0002]]` performed blind confirmation.
> 6. **Diagnostic Promotion:** `[[ACT-0002]]` promoted diagnostic to `{diag['status']}`.

---

## 4. Reproducibility
You do not have to take our word for it. 

1. Clone the repository: `git clone https://github.com/loom-research-system/loom-research-system.git`
2. Install dependencies: `pip install pyyaml`
3. Run the validator: `python loom_validator/validator.py .`
4. Expected output: `✓ All validation rules passed`

*Generated by Project Loom Publication Compiler v1.1 (Quartz Optimized)*
"""

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(md)
        
    print(f"✅ Quartz-Optimized Publication Bundle successfully generated!")
    print(f"📄 Location: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
